apiVersion: apps/v1
kind: Deployment
metadata:
  name: kooked-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kooked-operator
  template:
    metadata:
      labels:
        app: kooked-operator
    spec:
      serviceAccountName: operator-sa
      containers:
        - name: operator
          image: ghcr.io/kooked-ch/operator:1.0.1
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operator-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-rolebinding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: operator-sa
    namespace: kube-system
roleRef:
  kind: Role
  name: operator-role
  apiGroup: rbac.authorization.k8s.io
