apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-sa
  namespace: portal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-cluster-role
rules:
  # Core API permissions
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "secrets", "namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Apps permissions
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # CRD permissions
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Cert-manager permissions
  - apiGroups: ["cert-manager.io"]
    resources:
      ["clusterissuers", "certificates", "certificaterequests", "issuers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Custom resource permissions
  - apiGroups: ["kooked.ch"]
    resources: ["kookedapps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # RBAC permissions
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings", "roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Traefik permissions
  - apiGroups: ["traefik.containo.us"]
    resources:
      [
        "ingressroutes",
        "ingressroutetcps",
        "ingressrouteudps",
        "middlewares",
        "serverstransports",
        "tlsoptions",
        "tlsstores",
      ]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Events permissions for logging
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

  # Status permissions
  - apiGroups: ["kooked.ch"]
    resources: ["kookedapps/status"]
    verbs: ["get", "patch", "update"]

  # Storage permissions
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Network policy permissions
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # StatefulSet permissions
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: operator-sa
    namespace: portal
roleRef:
  kind: ClusterRole
  name: operator-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kooked-operator
  namespace: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kooked-operator
  template:
    metadata:
      labels:
        app: kooked-operator
    spec:
      serviceAccountName: operator-sa
      containers:
        - name: operator
          image: ghcr.io/kooked-ch/operator:3.1.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
