apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kookeddeployments.kooked.ch
spec:
  group: kooked.ch
  names:
    kind: KookedDeployment
    listKind: KookedDeploymentList
    plural: kookeddeployments
    singular: kookeddeployment
    shortNames:
      - kd
      - kdeploy
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Schema for the KookedDeployment API
          type: object
          properties:
            apiVersion:
              type: string
              description: API version of the KookedDeployment object.
            kind:
              type: string
              description: Kind of the object, always "KookedDeployment".
            metadata:
              type: object
            spec:
              type: object
              description: Desired state of the KookedDeployment
              properties:
                name:
                  type: string
                  description: Name of the deployment.
                project:
                  type: string
                  description: Project associated with the deployment.
                replicas:
                  type: integer
                  description: Number of replicas for the deployment.
                containers:
                  type: array
                  description: List of containers for the deployment.
                  items:
                    type: object
                    description: Container specification for the deployment.
                    properties:
                      name:
                        type: string
                        description: Name of the container.
                      image:
                        type: string
                        description: Docker image for the container.
                      environment:
                        type: array
                        description: Environment variables for the container.
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                              description: Name of the environment variable.
                            value:
                              type: string
                              description: Value of the environment variable.
                      domains:
                        type: array
                        description: Domains associated with the container.
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              description: URL of the domain.
                            port:
                              type: integer
                              description: Port for the domain.
                databases:
                  type: array
                  description: List of databases for the deployment.
                  items:
                    type: object
                    description: Database configuration for the deployment.
                    properties:
                      name:
                        type: string
                        description: Name of the database.
