apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kookedapps.kooked.ch
spec:
  group: kooked.ch
  names:
    plural: kookedapps
    singular: kookedapp
    kind: KookedApp
    shortNames:
      - kapp
      - kookedapp
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                containers:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      image:
                        type: string
                      env:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                      volumes:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            mountPath:
                              type: string
                databases:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      user:
                        type: string
                      password:
                        type: string
                      db:
                        type: string
                      provider:
                        type: string
                domains:
                  type: array
                  items:
                    type: object
                    properties:
                      url:
                        type: string
                      container:
                        type: string
                      port:
                        type: integer
      additionalPrinterColumns:
        - name: Project
          type: string
          description: Project associated with the deployment.
          jsonPath: .metadata.namespace
        - name: Replicas
          type: integer
          description: Number of replicas for the deployment.
          jsonPath: .spec.replicas
        - name: Age
          type: date
          description: Time since the deployment was created.
          jsonPath: .metadata.creationTimestamp
        - name: Status
          type: string
          description: Status phase of the deployment.
          jsonPath: .status.phase
        - name: Containers
          type: string
          description: Containers associated with the deployment.
          jsonPath: .spec.containers[*].name
          priority: 1
        - name: Domains
          type: string
          description: Domains associated with the deployment.
          jsonPath: .spec.domains[*].url
          priority: 1
        - name: Databases
          type: string
          description: Databases associated with the deployment.
          jsonPath: .spec.databases[*].name
          priority: 1
  subresources:
    status: {}
