apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kookeddeployments.kooked.ch
spec:
  group: kooked.ch
  names:
    kind: KookedDeployment
    listKind: KookedDeploymentList
    plural: kookeddeployments
    singular: kookeddeployment
    shortNames:
      - kd
      - kdeploy
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Schema for the KookedDeployment API
          type: object
          properties:
            apiVersion:
              type: string
              description: API version of the KookedDeployment object.
            kind:
              type: string
              description: Kind of the object, always "KookedDeployment".
            metadata:
              type: object
            spec:
              type: object
              description: Desired state of the KookedDeployment
              x-kubernetes-preserve-unknown-fields: true
              properties:
                name:
                  type: string
                  description: Name of the deployment.
                project:
                  type: string
                  description: Project associated with the deployment.
                user:
                  type: string
                  description: User who created the deployment.
                replicas:
                  type: integer
                  description: Number of replicas for the deployment.
                  default: 1
                containers:
                  type: array
                  description: List of containers for the deployment.
                  items:
                    type: object
                    description: Container specification for the deployment.
                    properties:
                      name:
                        type: string
                        description: Name of the container.
                      image:
                        type: string
                        description: Docker image for the container.
                      environment:
                        type: array
                        description: Environment variables for the container.
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                              description: Name of the environment variable.
                            value:
                              type: string
                              description: Value of the environment variable.
                      domains:
                        type: array
                        description: Domains associated with the container.
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              description: URL of the domain.
                            port:
                              type: integer
                              description: Port for the domain.
                databases:
                  type: array
                  description: List of databases for the deployment.
                  items:
                    type: object
                    description: Database configuration for the deployment.
                    properties:
                      name:
                        type: string
                        description: Name of the database.
              required:
                - name
                - project
                - containers
                - user
            status:
              type: object
              description: Status defines the observed state of the KookedDeployment.
              x-kubernetes-preserve-unknown-fields: true
              properties:
                phase:
                  type: string
                  description: Current phase of the deployment.
                history:
                  type: array
                  description: History of the KookedDeployment.
                  items:
                    type: object
                    description: History entry for the deployment.
                    properties:
                      timestamp:
                        type: string
                        description: Timestamp of the history entry.
                      action:
                        type: string
                        description: Action performed on the deployment.
                      user:
                        type: string
                        description: User who performed the action.
                      message:
                        type: string
                        description: Message associated with the action.
      additionalPrinterColumns:
        - name: Project
          type: string
          description: Project associated with the deployment.
          jsonPath: .spec.project
        - name: Replicas
          type: integer
          description: Number of replicas for the deployment.
          jsonPath: .spec.replicas
        - name: Age
          type: date
          description: Time since the deployment was created.
          jsonPath: .metadata.creationTimestamp
        - name: Status
          type: string
          description: Status phase of the deployment.
          jsonPath: .status.phase
        - name: Containers
          type: string
          description: Containers associated with the deployment.
          jsonPath: .spec.containers[*].name
          priority: 1
        - name: Domains
          type: string
          description: Domains associated with the deployment.
          jsonPath: .spec.containers[*].domains[*].url
          priority: 1
        - name: Databases
          type: string
          description: Databases associated with the deployment.
          jsonPath: .spec.databases[*].name
          priority: 1
      subresources:
        status: {}
